
import React, { useEffect, useRef } from 'react';
import { ChatMessage } from '../types';
import MarkdownRenderer from './MarkdownRenderer';
import { Bot, User, Cpu, Zap } from 'lucide-react';

interface MessageListProps {
  messages: ChatMessage[];
  isLoading: boolean;
  currentModel: string;
}

const MessageList: React.FC<MessageListProps> = ({ messages, isLoading, currentModel }) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  // Video Renderer Helper
  const renderContent = (content: string) => {
      // Check for HTML video tag (generated by our Video mode)
      if (content.includes('<video')) {
          return <div dangerouslySetInnerHTML={{ __html: content }} />;
      }
      return <MarkdownRenderer content={content} />;
  };

  if (messages.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-neutral-500 p-8 bg-neutral-950">
        <div className="w-28 h-28 bg-neutral-900 rounded-3xl flex items-center justify-center mb-6 border border-yellow-500/20 shadow-[0_0_50px_-12px_rgba(234,179,8,0.15)] relative group">
          <Cpu size={56} className="text-yellow-500 group-hover:scale-110 transition-transform duration-500" />
          <div className="absolute -top-2 -right-2 bg-green-500 w-5 h-5 rounded-full border-4 border-neutral-950 animate-pulse"></div>
        </div>
        <h3 className="text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-b from-yellow-300 to-yellow-600 mb-3 tracking-tight">
          Fredbear555Ai <span className="text-lg text-neutral-600 font-normal block md:inline md:ml-2">Golden Edition</span>
        </h3>
        <p className="text-center max-w-md mb-10 text-neutral-400 leading-relaxed">
          Core: <span className="text-yellow-400 font-semibold">Hybrid V2.7</span> • Engine: <span className="text-orange-400 font-mono">{currentModel}</span>
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 w-full max-w-2xl">
            {['Solve Calculus Problem', 'Audit Python Code', 'Generate 4K Gold Image', 'Create Cinematic Video'].map((suggestion, i) => (
                <div key={i} className="p-4 border border-neutral-800 rounded-xl bg-neutral-900/50 text-sm text-neutral-300 text-center hover:bg-neutral-800 hover:border-yellow-500/40 hover:text-yellow-300 transition-all cursor-pointer shadow-sm hover:shadow-yellow-500/10">
                    "{suggestion}"
                </div>
            ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 md:p-6 scroll-smooth bg-neutral-950 custom-scrollbar">
      <div className="max-w-3xl mx-auto space-y-8">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
            <div className={`shrink-0 w-10 h-10 rounded-xl flex items-center justify-center mt-1 shadow-lg
              ${msg.role === 'user' 
                ? 'bg-neutral-800 text-neutral-400 border border-neutral-700' 
                : 'bg-gradient-to-br from-yellow-400 to-orange-600 text-black shadow-yellow-500/20'
              }`}
            >
              {msg.role === 'user' ? <User size={20} /> : <Bot size={20} />}
            </div>
            <div className={`flex flex-col max-w-[85%] md:max-w-[80%] space-y-2 ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              
              {/* Optimized Image Grid for 3 Images */}
              {msg.attachments && msg.attachments.length > 0 && (
                <div className={`grid gap-2 mb-2 w-full
                    ${msg.attachments.length === 1 ? 'grid-cols-1 max-w-[300px]' : 
                      msg.attachments.length === 2 ? 'grid-cols-2' : 
                      'grid-cols-3' /* Perfect for 3 images */}
                `}>
                  {msg.attachments.map((att, i) => (
                    <div key={i} className="relative aspect-square">
                        <img 
                            src={`data:${att.mimeType};base64,${att.data}`} 
                            alt={att.name} 
                            className="rounded-xl w-full h-full object-cover border border-neutral-700 shadow-md hover:scale-105 transition-transform duration-300" 
                        />
                    </div>
                  ))}
                </div>
              )}
              
              <div className={`rounded-2xl px-6 py-4 shadow-md text-base leading-relaxed border
                ${msg.role === 'user' 
                  ? 'bg-neutral-800/80 text-yellow-50 border-neutral-700 rounded-tr-none' 
                  : 'bg-neutral-900/90 border-yellow-500/20 text-yellow-100 rounded-tl-none shadow-[0_4px_20px_-5px_rgba(234,179,8,0.1)]'
                }`}
              >
                {msg.role === 'model' ? renderContent(msg.content) : <div className="whitespace-pre-wrap">{msg.content}</div>}
              </div>
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex gap-4">
            <div className="shrink-0 w-10 h-10 rounded-xl bg-yellow-500/10 border border-yellow-500/30 text-yellow-500 flex items-center justify-center mt-1"><Bot size={20} /></div>
            <div className="flex items-center gap-1 h-10">
              <span className="w-2 h-2 bg-yellow-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></span>
              <span className="w-2 h-2 bg-yellow-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></span>
              <span className="w-2 h-2 bg-yellow-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></span>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>
    </div>
  );
};

export default MessageList;
