
import React, { useEffect, useRef } from 'react';
import { ChatMessage } from '../types';
import MarkdownRenderer from './MarkdownRenderer';
import { Bot, User, Cpu, Zap } from 'lucide-react';

interface MessageListProps {
  messages: ChatMessage[];
  isLoading: boolean;
  currentModel: string;
}

const MessageList: React.FC<MessageListProps> = ({ messages, isLoading, currentModel }) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  // Video Renderer Helper
  const renderContent = (content: string) => {
      // Check for HTML video tag (generated by our Video mode)
      if (content.includes('<video')) {
          // Dangerous but necessary for video tag injection from our trusted service
          return <div dangerouslySetInnerHTML={{ __html: content }} />;
      }
      return <MarkdownRenderer content={content} />;
  };

  if (messages.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-gray-500 p-8 bg-white">
        <div className="w-24 h-24 bg-gradient-to-br from-white to-gray-50 rounded-2xl flex items-center justify-center mb-6 border border-gray-200 shadow-xl relative">
          <Cpu size={48} className="text-orange-500" />
          <div className="absolute -top-2 -right-2 bg-green-500 w-4 h-4 rounded-full border-2 border-white animate-pulse"></div>
        </div>
        <h3 className="text-2xl font-bold text-gray-800 mb-2">Fredbear555Ai White</h3>
        <p className="text-center max-w-md mb-8 text-gray-500">
          Core: <span className="text-blue-600 font-semibold">Hybrid V2.7 (GPT+Gemini+X)</span><br/>
          Engine: <span className="text-orange-500 font-mono">{currentModel}</span>
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 w-full max-w-2xl">
            {['Analyze Quantum Physics (150 IQ)', 'Create a Python Game', 'Generate 4K Image of Cyberpunk City', 'Create Video of Cat Driving'].map((suggestion, i) => (
                <div key={i} className="p-4 border border-gray-200 rounded-xl bg-white text-sm text-gray-600 text-center hover:bg-gray-50 hover:border-orange-200 transition-all cursor-pointer shadow-sm">
                    "{suggestion}"
                </div>
            ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 md:p-6 scroll-smooth bg-white">
      <div className="max-w-3xl mx-auto space-y-6">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
            <div className={`shrink-0 w-8 h-8 rounded-lg flex items-center justify-center mt-1
              ${msg.role === 'user' 
                ? 'bg-gray-200 text-gray-600' 
                : 'bg-gradient-to-br from-orange-500 to-red-600 text-white shadow-md shadow-orange-500/20'
              }`}
            >
              {msg.role === 'user' ? <User size={16} /> : <Bot size={16} />}
            </div>
            <div className={`flex flex-col max-w-[85%] md:max-w-[80%] space-y-2 ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              {msg.attachments && msg.attachments.length > 0 && (
                <div className="flex flex-wrap gap-2 mb-2 justify-end">
                  {msg.attachments.map((att, i) => (
                    <img key={i} src={`data:${att.mimeType};base64,${att.data}`} alt={att.name} className="rounded-lg max-w-[200px] max-h-[200px] object-cover border border-gray-200 shadow-sm" />
                  ))}
                </div>
              )}
              <div className={`rounded-2xl px-5 py-4 shadow-sm text-base leading-relaxed
                ${msg.role === 'user' 
                  ? 'bg-gray-100 text-gray-800 rounded-tr-none border border-gray-200' 
                  : 'bg-white border border-gray-100 text-gray-800 rounded-tl-none shadow-[0_2px_8px_-2px_rgba(0,0,0,0.05)]'
                }`}
              >
                {msg.role === 'model' ? renderContent(msg.content) : <div className="whitespace-pre-wrap">{msg.content}</div>}
              </div>
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex gap-4">
            <div className="shrink-0 w-8 h-8 rounded-lg bg-orange-600 text-white flex items-center justify-center mt-1 shadow-md"><Bot size={16} /></div>
            <div className="flex items-center gap-1 h-8">
              <span className="w-2 h-2 bg-orange-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></span>
              <span className="w-2 h-2 bg-orange-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></span>
              <span className="w-2 h-2 bg-orange-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></span>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>
    </div>
  );
};

export default MessageList;
